name: build

on:

  # Manual rebuild, in case of some important upstream change
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache maven packages
        uses: actions/cache@v2
        env:
          cache-name: cache-mvn2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: add arm64 docker binfmt
        run: docker run --privileged --rm tonistiigi/binfmt --install arm64,arm

      - name: Build with Maven
        run: mvn -B compile

      - name: Run tests
        run: mvn -B test

      - name: Build package
        run: mvn -B package
